imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    default_locale:  "%locale%"
    #translator:      { fallback: en }
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path: ~
        # On Debian/Ubuntu session files are deleted by a cron job and directory
        # permissions prevent PHP from reading the session directory. This makes
        # all attempts by PHP to clean the sessions itself fail. Setting
        # gc_probability to 0 avoids such failures.
        gc_probability: 0
    fragments:       ~
    http_method_override: true
    assets: ~
    cache:
        pools:
            # Cache pool for all GitHub API requests done through
            # GithubApiService
            app.cache.githubapi:
                adapter: cache.app

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.project_dir%/sitecontent": site_content
    # Use Bootstrap Form styling by default
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'LibrecoresProjectRepoBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - LibrecoresProjectRepoBundle
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        cssrewrite: ~
        jsqueeze: ~
    assets:
        # JavaScript files loaded inside <head> (only for special cases)
        js_head:
            inputs:
                - "assets/js/respond.min.js"
                - "assets/js/html5shiv.min.js"

        # JavaScript files loaded at the bottom of <body> (preferred)
        js_body_end:
            inputs:
                - "assets/js/jquery.min.js"
                - "assets/js/bootstrap.min.js"
                - "assets/js/moment.min.js"
                - "assets/js/livestamp.js"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_520_ci

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            datetime_functions:
                DAY: 'DoctrineExtensions\Query\Mysql\Day'
                WEEK: 'DoctrineExtensions\Query\Mysql\Week'
                MONTH: 'DoctrineExtensions\Query\Mysql\Month'
                YEAR: 'DoctrineExtensions\Query\Mysql\Year'
        hydrators:
            group: 'Librecores\ProjectRepoBundle\Doctrine\Hydrators\GroupHydrator'

# Doctrine Migrations
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: 'Application\Migrations'
    table_name: migration_versions
    name: 'LibreCores Migrations'

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }


# SimplePie (RSS/Atom Parser) Configuration
# Docs: http://simplepie.org/wiki/faq/how_does_simplepie_s_caching_http_conditional_get_system_work
fkr_simple_pie:
    cache_enabled: true
    cache_dir: '%kernel.cache_dir%/rss'
    cache_duration: 3600

# RabbitMQ Configuration
old_sound_rabbit_mq:
    connections:
        default:
            host:     "%rabbitmq_host%"
            port:     "%rabbitmq_port%"
            user:     "%rabbitmq_user%"
            password: "%rabbitmq_password%"
            vhost:    '/'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0
    producers:
        update_project_info:
            connection:       default
            exchange_options: {name: 'update-project-info', type: direct}
    consumers:
        update_project_info:
            connection:       default
            exchange_options: {name: 'update-project-info', type: direct}
            queue_options:    {name: 'update-project-info'}
            callback:         update_project_info_service

# FOSUser Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: 'Librecores\ProjectRepoBundle\Entity\User'
    service:
        user_manager: librecores_user_manager
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:        'noreply@librecores.org'
        sender_name:    'LibreCores'
    registration:
        confirmation:
            from_email:
                address:        'noreply@librecores.org'
                sender_name:    'LibreCores'
            enabled:    "%user_email_confirmation_enabled%"
            template:   'FOSUserBundle:Registration:email.html.twig'

# HWI OAuth Configuration
hwi_oauth:
    connect:
        confirmation: false
        account_connector: librecores_user_provider
    firewall_names: [main]
    resource_owners:
        github:
            type:                github
            client_id:           "%github_app_id%"
            client_secret:       "%github_app_secret%"
            scope:               "user:email admin:repo_hook read:org"
            options:
                csrf:            true
        google:
            type:                google
            client_id:           "%google_app_id%"
            client_secret:       "%google_app_secret%"
            scope:               "email profile"

# sentry
sentry:
    dsn: "%sentry_dsn%"
    options:
        environment: "%sentry_env%"

algolia_search:
  indices:
    - name: projects
      class: Librecores\ProjectRepoBundle\Entity\Project

    - name: classifications
      class: Librecores\ProjectRepoBundle\Entity\ProjectClassification
