# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Twig date extension - http://twig-extensions.readthedocs.io/en/latest/date.html
    Twig\Extensions\DateExtension:
        autowire: false
        # Autowire inject a TranslatorInterface into the constructor of the extension. If that happens, the extension
        # thinks it can be translated -- but we don't have any translations available, therefore the autowire is set to
        # false

    user_normalizer:
        class: Librecores\ProjectRepoBundle\Serializer\Normalizer\UserNormalizer
        tag: serializer.normalizer
        public: false

    project_normalizer:
        class: Librecores\ProjectRepoBundle\Serializer\Normalizer\ProjectNormalizer
        tag: serializer.normalizer
        public: false

    organization_normalizer:
        class: Librecores\ProjectRepoBundle\Serializer\Normalizer\OrganizationNormalizer
        tag: serializer.normalizer
        public: false

framework:
  serializer: { enabled: true }
